### ISSUE TITLE
如果子应用的挂载DOM在父应用里应该怎么办？

### ISSUE THREAD

**Issue by Vibing** [QxQstar/single-spa-vue#1]
![](https://tva1.sinaimg.cn/large/006y8mN6ly1g8jpfy5zotj30ku0at3yk.jpg)

子应用想要挂载在Content里，外面的Main应用是整个项目基础，有好的解决办法吗

**Comment by QxQstar** [comment]
```
const vueLifecycles = singleSpaVue({
  Vue:vue,
  appOptions: {
    el:'#content',
    render: (h) => h(App),
    router,
    store
  },
});
```
让el对应的#content是content里的一个节点

**Comment by Vibing** [comment]
可是 content 在 Main 应用里，怎么能保证 Main 应用和子应用的加载顺序呢

**Comment by QxQstar** [comment]
你可能等main应用中的content装载到界面之后才注册各个子应该，在我的demo中就是这样做的

**Comment by zhaichong** [comment]
你好通过登录页面进来以后，点击导航 则跳转到新的页面去了 这种应该是使用子路由我看源码中没使用，请大神指教一下
如图
![image](https://user-images.githubusercontent.com/6859292/68929763-ef209e00-07c7-11ea-9f5f-7e6281687f1c.png)

![image](https://user-images.githubusercontent.com/6859292/68929775-f5af1580-07c7-11ea-96a6-36d2acbe8580.png)
![image](https://user-images.githubusercontent.com/6859292/68929794-fd6eba00-07c7-11ea-8492-2d95840b1f31.png)

**Comment by QxQstar** [comment]
你是不是想在进入localhost:5000/app1/nihao的时候，还显示localhost:5000页面上的导航？如果想要这样，你需要在调用singleSpa.registerApplication方法注册localhost:5000项目的时候让singleSpa.registerApplication的第三个参数始终返回为true，同时还需要确定localhost:5000/app1/nihao的装载点与localhost:5000的装载点不一样。

**Comment by zhaichong** [comment]
你好，是就是想跳转下级的时候还保留导航，我这个项目是从官方下载的，我看了一下singleSpa.registerApplication第三个参数一直是true，装载点也是不一样。我能加您微信或者qq之类的吗。我的QQ是285778942 微信是zhaichong07
